// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4980.AARobot2014;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightFront;
    public static SpeedController driveTrainRightBack;
    public static SpeedController driveTrainLeftFront;
    public static SpeedController driveTrainLeftBack;
    public static RobotDrive driveTrainRobotDrive41;
    public static SpeedController armElevator;
    public static SpeedController armWheelsWheelMotor;
    public static Ultrasonic armWheelsUltrasonic;
    public static SpeedController kickerKickerMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightFront = new Talon(1, 1);
	LiveWindow.addActuator("Drive Train", "RightFront", (Talon) driveTrainRightFront);
        
        driveTrainRightBack = new Talon(1, 2);
	LiveWindow.addActuator("Drive Train", "RightBack", (Talon) driveTrainRightBack);
        
        driveTrainLeftFront = new Talon(1, 3);
	LiveWindow.addActuator("Drive Train", "LeftFront", (Talon) driveTrainLeftFront);
        
        driveTrainLeftBack = new Talon(1, 4);
	LiveWindow.addActuator("Drive Train", "LeftBack", (Talon) driveTrainLeftBack);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFront, driveTrainLeftBack,
              driveTrainRightFront, driveTrainRightBack);
	
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        armElevator = new Talon(1, 5);
	LiveWindow.addActuator("Arm", "Elevator", (Talon) armElevator);
        
        armWheelsWheelMotor = new Talon(1, 6);
	LiveWindow.addActuator("ArmWheels", "WheelMotor", (Talon) armWheelsWheelMotor);
        
        armWheelsUltrasonic = new Ultrasonic(1, 1, 1, 2);
	LiveWindow.addSensor("ArmWheels", "Ultrasonic", armWheelsUltrasonic);
        
        kickerKickerMotor = new Talon(1, 7);
	LiveWindow.addActuator("Kicker", "KickerMotor", (Talon) kickerKickerMotor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armWheelsUltrasonic.setAutomaticMode(true);	
    }
}
