// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4980.AARobot2014;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder driveTrainRightBackEncoder;
    public static Encoder driveTrainRightFrontEncoder;
    public static SpeedController driveTrainRightFront;
    public static SpeedController driveTrainRightBack;
    public static SpeedController driveTrainLeftFront;
    public static SpeedController driveTrainLeftBack;
    public static RobotDrive driveTrainRobotDrive41;
    public static Accelerometer driveTrainAccelerometer;
    public static Encoder driveTrainLeftFrontEncoder;
    public static Encoder driveTrainLeftBackEncoder;
    public static DigitalInput driveTrainGryo;
    public static SpeedController armElevator;
    public static SpeedController armWheelsWheelMotor;
    public static Ultrasonic armWheelsUltrasonic;
    public static SpeedController kickerKickerMotor;
    public static Servo cameraPanServo;
    public static Servo cameraTiltServo;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightBackEncoder = new Encoder(1, 5, 1, 6, false, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "RightBack Encoder", driveTrainRightBackEncoder);
        driveTrainRightBackEncoder.setDistancePerPulse(1.0);
        driveTrainRightBackEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainRightBackEncoder.start();
        driveTrainRightFrontEncoder = new Encoder(1, 3, 1, 4, true, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "RightFront Encoder", driveTrainRightFrontEncoder);
        driveTrainRightFrontEncoder.setDistancePerPulse(1.0);
        driveTrainRightFrontEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainRightFrontEncoder.start();
        driveTrainRightFront = new Talon(1, 1);
	LiveWindow.addActuator("Drive Train", "RightFront", (Talon) driveTrainRightFront);
        
        driveTrainRightBack = new Talon(1, 2);
	LiveWindow.addActuator("Drive Train", "RightBack", (Talon) driveTrainRightBack);
        
        driveTrainLeftFront = new Talon(1, 3);
	LiveWindow.addActuator("Drive Train", "LeftFront", (Talon) driveTrainLeftFront);
        
        driveTrainLeftBack = new Talon(1, 4);
	LiveWindow.addActuator("Drive Train", "LeftBack", (Talon) driveTrainLeftBack);
        
        driveTrainRobotDrive41 = new RobotDrive(driveTrainLeftFront, driveTrainLeftBack,
              driveTrainRightFront, driveTrainRightBack);
	
        driveTrainRobotDrive41.setSafetyEnabled(true);
        driveTrainRobotDrive41.setExpiration(0.1);
        driveTrainRobotDrive41.setSensitivity(0.5);
        driveTrainRobotDrive41.setMaxOutput(1.0);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainAccelerometer = new Accelerometer(1, 1);
	LiveWindow.addSensor("Drive Train", "Accelerometer", driveTrainAccelerometer);
        driveTrainAccelerometer.setSensitivity(1.0);
        driveTrainAccelerometer.setZero(2.5);
        driveTrainLeftFrontEncoder = new Encoder(1, 7, 1, 8, false, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "LeftFront Encoder", driveTrainLeftFrontEncoder);
        driveTrainLeftFrontEncoder.setDistancePerPulse(1.0);
        driveTrainLeftFrontEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainLeftFrontEncoder.start();
        driveTrainLeftBackEncoder = new Encoder(1, 9, 1, 10, false, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "LeftBack Encoder", driveTrainLeftBackEncoder);
        driveTrainLeftBackEncoder.setDistancePerPulse(1.0);
        driveTrainLeftBackEncoder.setPIDSourceParameter(PIDSourceParameter.kRate);
        driveTrainLeftBackEncoder.start();
        driveTrainGryo = new DigitalInput(1, 11);
	LiveWindow.addSensor("Drive Train", "Gryo", driveTrainGryo);
        
        armElevator = new Talon(1, 5);
	LiveWindow.addActuator("Arm", "Elevator", (Talon) armElevator);
        
        armWheelsWheelMotor = new Talon(1, 6);
	LiveWindow.addActuator("ArmWheels", "WheelMotor", (Talon) armWheelsWheelMotor);
        
        armWheelsUltrasonic = new Ultrasonic(1, 1, 1, 2);
	LiveWindow.addSensor("ArmWheels", "Ultrasonic", armWheelsUltrasonic);
        
        kickerKickerMotor = new Talon(1, 7);
	LiveWindow.addActuator("Kicker", "KickerMotor", (Talon) kickerKickerMotor);
        
        cameraPanServo = new Servo(1, 9);
	LiveWindow.addActuator("Camera", "Pan Servo", cameraPanServo);
        
        cameraTiltServo = new Servo(1, 10);
	LiveWindow.addActuator("Camera", "Tilt Servo", cameraTiltServo);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        armWheelsUltrasonic.setAutomaticMode(true);	
    }
}
