// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4980.AARobot2014.subsystems;
import org.usfirst.frc4980.AARobot2014.RobotMap;
import org.usfirst.frc4980.AARobot2014.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rightFront = RobotMap.driveTrainRightFront;
    SpeedController rightBack = RobotMap.driveTrainRightBack;
    SpeedController leftFront = RobotMap.driveTrainLeftFront;
    SpeedController leftBack = RobotMap.driveTrainLeftBack;
    RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new MecanumDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void mecanumDrive(Joystick stick){
        
        //robotDrive41.mecanumDrive_Cartesian(stick.getX(), stick.getY(),stick.getTwist(),0);
        robotDrive41.mecanumDrive_Polar(stick.getMagnitude(),stick.getDirectionDegrees(),stick.getTwist());
    }
    
    public void driveForward(double speed){
        robotDrive41.drive(speed, 0);
    }
}
